# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - petstore/petstoreproductservice/*

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '673b08f0-7e8e-429a-a62f-07defed93708'
  imageRepository: 'petstoreproductservice'
  containerRegistry: 'hsazurepetstorecr.azurecr.io'
  dockerfilePath: 'petstore/petstoreproductservice/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'hsazurepetstorecr1969c567-auth'

stages:
- stage: Deploy
  displayName: Deploy Stage
  #dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy App
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'hsazurepetstore-akscluster-ingress-petstoreservices-1438'
              namespace: 'ingress-petstoreservices'
              secretType: 'dockerRegistry'
              secretName: '$(imagePullSecret)'
              dockerRegistryEndpoint: '$(dockerRegistryServiceConnection)'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: hsazurepetstore-akscluster-ingress-petstoreservices-1438
              namespace: ingress-petstoreservices
              manifests: |
                $(Pipeline.Workspace)/manifests/petstoreproductservice-deployment-everything-enabled.yml
                $(Pipeline.Workspace)/manifests/petstoreproductservice-service-everything-enabled.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):latest
